"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PACKAGE_NAME = exports.VERSION = exports.createAuditLogger = exports.ContextualAuditLogger = exports.InMemoryAuditLogger = exports.PermissionChecker = exports.RBACEngine = exports.hierarchyUtils = exports.RoleHierarchyResolver = exports.permissionMatcher = exports.PermissionMatcher = exports.wildcardParser = exports.WildcardParser = exports.CircularHierarchyError = exports.RoleNotFoundError = exports.PermissionDeniedError = exports.RBACErrorCode = exports.RBACError = exports.DEFAULT_VALIDATION_OPTIONS = exports.DEFAULT_PERFORMANCE_OPTIONS = exports.DEFAULT_MULTI_TENANCY_OPTIONS = exports.DEFAULT_PERMISSION_OPTIONS = exports.DEFAULT_HIERARCHY_OPTIONS = exports.DEFAULT_AUDIT_OPTIONS = exports.DEFAULT_CACHE_OPTIONS = exports.mergeOptions = exports.NoOpAuditLogger = exports.AuditSeverity = exports.AuditAction = exports.InMemoryCache = exports.DefaultCacheKeyGenerator = void 0;
var interfaces_1 = require("./interfaces");
Object.defineProperty(exports, "DefaultCacheKeyGenerator", { enumerable: true, get: function () { return interfaces_1.DefaultCacheKeyGenerator; } });
Object.defineProperty(exports, "InMemoryCache", { enumerable: true, get: function () { return interfaces_1.InMemoryCache; } });
Object.defineProperty(exports, "AuditAction", { enumerable: true, get: function () { return interfaces_1.AuditAction; } });
Object.defineProperty(exports, "AuditSeverity", { enumerable: true, get: function () { return interfaces_1.AuditSeverity; } });
Object.defineProperty(exports, "NoOpAuditLogger", { enumerable: true, get: function () { return interfaces_1.NoOpAuditLogger; } });
var types_1 = require("./types");
Object.defineProperty(exports, "mergeOptions", { enumerable: true, get: function () { return types_1.mergeOptions; } });
Object.defineProperty(exports, "DEFAULT_CACHE_OPTIONS", { enumerable: true, get: function () { return types_1.DEFAULT_CACHE_OPTIONS; } });
Object.defineProperty(exports, "DEFAULT_AUDIT_OPTIONS", { enumerable: true, get: function () { return types_1.DEFAULT_AUDIT_OPTIONS; } });
Object.defineProperty(exports, "DEFAULT_HIERARCHY_OPTIONS", { enumerable: true, get: function () { return types_1.DEFAULT_HIERARCHY_OPTIONS; } });
Object.defineProperty(exports, "DEFAULT_PERMISSION_OPTIONS", { enumerable: true, get: function () { return types_1.DEFAULT_PERMISSION_OPTIONS; } });
Object.defineProperty(exports, "DEFAULT_MULTI_TENANCY_OPTIONS", { enumerable: true, get: function () { return types_1.DEFAULT_MULTI_TENANCY_OPTIONS; } });
Object.defineProperty(exports, "DEFAULT_PERFORMANCE_OPTIONS", { enumerable: true, get: function () { return types_1.DEFAULT_PERFORMANCE_OPTIONS; } });
Object.defineProperty(exports, "DEFAULT_VALIDATION_OPTIONS", { enumerable: true, get: function () { return types_1.DEFAULT_VALIDATION_OPTIONS; } });
var errors_1 = require("./errors");
Object.defineProperty(exports, "RBACError", { enumerable: true, get: function () { return errors_1.RBACError; } });
Object.defineProperty(exports, "RBACErrorCode", { enumerable: true, get: function () { return errors_1.RBACErrorCode; } });
Object.defineProperty(exports, "PermissionDeniedError", { enumerable: true, get: function () { return errors_1.PermissionDeniedError; } });
Object.defineProperty(exports, "RoleNotFoundError", { enumerable: true, get: function () { return errors_1.RoleNotFoundError; } });
Object.defineProperty(exports, "CircularHierarchyError", { enumerable: true, get: function () { return errors_1.CircularHierarchyError; } });
var utils_1 = require("./utils");
Object.defineProperty(exports, "WildcardParser", { enumerable: true, get: function () { return utils_1.WildcardParser; } });
Object.defineProperty(exports, "wildcardParser", { enumerable: true, get: function () { return utils_1.wildcardParser; } });
Object.defineProperty(exports, "PermissionMatcher", { enumerable: true, get: function () { return utils_1.PermissionMatcher; } });
Object.defineProperty(exports, "permissionMatcher", { enumerable: true, get: function () { return utils_1.permissionMatcher; } });
Object.defineProperty(exports, "RoleHierarchyResolver", { enumerable: true, get: function () { return utils_1.RoleHierarchyResolver; } });
Object.defineProperty(exports, "hierarchyUtils", { enumerable: true, get: function () { return utils_1.hierarchyUtils; } });
var services_1 = require("./services");
Object.defineProperty(exports, "RBACEngine", { enumerable: true, get: function () { return services_1.RBACEngine; } });
Object.defineProperty(exports, "PermissionChecker", { enumerable: true, get: function () { return services_1.PermissionChecker; } });
Object.defineProperty(exports, "InMemoryAuditLogger", { enumerable: true, get: function () { return services_1.InMemoryAuditLogger; } });
Object.defineProperty(exports, "ContextualAuditLogger", { enumerable: true, get: function () { return services_1.ContextualAuditLogger; } });
Object.defineProperty(exports, "createAuditLogger", { enumerable: true, get: function () { return services_1.createAuditLogger; } });
exports.VERSION = '1.0.0';
exports.PACKAGE_NAME = '@prodforcode/rbac-core';
//# sourceMappingURL=index.js.map